from typing import Protocol
from asyncio import Queue


class Source(Protocol):
    queue: Queue

    async def open(self, queue: Queue) -> None: ...
    async def put(self, num: int) -> None: ...
    async def multi_put(self, num: int) -> None: ...
    async def close(self) -> None: ...
